instruments = [
    ("Piano", "Acoustic Grand Piano"),
    ("Piano", "Bright Acoustic Piano"),
    ("Piano", "Electric Grand Piano"),
    ("Piano", "Honky-tonk Piano"),
    ("Piano", "Rhodes Piano"),
    ("Piano", "Chorused Piano"),
    ("Piano", "Harpsichord"),
    ("Piano", "Clavinet"),
    ("Chromatic Percussion", "Celesta"),
    ("Chromatic Percussion", "Glockenspiel"),
    ("Chromatic Percussion", "Music box"),
    ("Chromatic Percussion", "Vibraphone"),
    ("Chromatic Percussion", "Marimba"),
    ("Chromatic Percussion", "Xylophone"),
    ("Chromatic Percussion", "Tubular Bells"),
    ("Chromatic Percussion", "Dulcimer"),
    ("Organ", "Hammond Organ"),
    ("Organ", "Percussive Organ"),
    ("Organ", "Rock Organ"),
    ("Organ", "Church Organ"),
    ("Organ", "Reed Organ"),
    ("Organ", "Accordion"),
    ("Organ", "Harmonica"),
    ("Organ", "Tango Accordion"),
    ("Guitar", "Acoustic Guitar (nylon)"),
    ("Guitar", "Acoustic Guitar (steel)"),
    ("Guitar", "Electric Guitar (jazz)"),
    ("Guitar", "Electric Guitar (clean)"),
    ("Guitar", "Electric Guitar (muted)"),
    ("Guitar", "Overdriven Guitar"),
    ("Guitar", "Distortion Guitar"),
    ("Guitar", "Guitar Harmonics"),
    ("Bass", "Acoustic Bass"),
    ("Bass", "Electric Bass (finger)"),
    ("Bass", "Electric Bass (pick)"),
    ("Bass", "Fretless Bass"),
    ("Bass", "Slap Bass 1"),
    ("Bass", "Slap Bass 2"),
    ("Bass", "Synth Bass 1"),
    ("Bass", "Synth Bass 2"),
    ("Strings", "Violin"),
    ("Strings", "Viola"),
    ("Strings", "Cello"),
    ("Strings", "Contrabass"),
    ("Strings", "Tremolo Strings"),
    ("Strings", "Pizzicato Strings"),
    ("Strings", "Orchestral Harp"),
    ("Strings", "Timpani"),
    ("Ensemble", "String Ensemble 1"),
    ("Ensemble", "String Ensemble 2"),
    ("Ensemble", "Synth Strings 1"),
    ("Ensemble", "Synth Strings 2"),
    ("Ensemble", "Choir Aahs"),
    ("Ensemble", "Voice Oohs"),
    ("Ensemble", "Synth Voice"),
    ("Ensemble", "Orchestra Hit"),
    ("Brass", "Trumpet"),
    ("Brass", "Trombone"),
    ("Brass", "Tuba"),
    ("Brass", "Muted Trumpet"),
    ("Brass", "French Horn"),
    ("Brass", "Brass Section"),
    ("Brass", "Synth Brass 1"),
    ("Brass", "Synth Brass 2"),
    ("Reed", "Soprano Sax"),
    ("Reed", "Alto Sax"),
    ("Reed", "Tenor Sax"),
    ("Reed", "Baritone Sax"),
    ("Reed", "Oboe"),
    ("Reed", "English Horn"),
    ("Reed", "Bassoon"),
    ("Reed", "Clarinet"),
    ("Pipe", "Piccolo"),
    ("Pipe", "Flute"),
    ("Pipe", "Recorder"),
    ("Pipe", "Pan Flute"),
    ("Pipe", "Bottle Blow"),
    ("Pipe", "Shakuhachi"),
    ("Pipe", "Whistle"),
    ("Pipe", "Ocarina"),
    ("Synth Lead", "Lead 1 (square)"),
    ("Synth Lead", "Lead 2 (sawtooth)"),
    ("Synth Lead", "Lead 3 (calliope lead)"),
    ("Synth Lead", "Lead 4 (chiffer lead)"),
    ("Synth Lead", "Lead 5 (charang)"),
    ("Synth Lead", "Lead 6 (voice)"),
    ("Synth Lead", "Lead 7 (fifths)"),
    ("Synth Lead", "Lead 8 (brass + lead)"),
    ("Synth Pad", "Pad 1 (new age)"),
    ("Synth Pad", "Pad 2 (warm)"),
    ("Synth Pad", "Pad 3 (polysynth)"),
    ("Synth Pad", "Pad 4 (choir)"),
    ("Synth Pad", "Pad 5 (bowed)"),
    ("Synth Pad", "Pad 6 (metallic)"),
    ("Synth Pad", "Pad 7 (halo)"),
    ("Synth Pad", "Pad 8 (sweep)"),
    ("Synth Effects", "FX 1 (rain)"),
    ("Synth Effects", "FX 2 (soundtrack)"),
    ("Synth Effects", "FX 3 (crystal)"),
    ("Synth Effects", "FX 4 (atmosphere)"),
    ("Synth Effects", "FX 5 (brightness)"),
    ("Synth Effects", "FX 6 (goblins)"),
    ("Synth Effects", "FX 7 (echoes)"),
    ("Synth Effects", "FX 8 (sci-fi)"),
    ("Ethnic", "Sitar"),
    ("Ethnic", "Banjo"),
    ("Ethnic", "Shamisen"),
    ("Ethnic", "Koto"),
    ("Ethnic", "Kalimba"),
    ("Ethnic", "Bagpipe"),
    ("Ethnic", "Fiddle"),
    ("Ethnic", "Shana"),
    ("Percussive", "Tinkle Bell"),
    ("Percussive", "Agogo"),
    ("Percussive", "Steel Drums"),
    ("Percussive", "Woodblock"),
    ("Percussive", "Taiko Drum"),
    ("Percussive", "Melodic Tom"),
    ("Percussive", "Synth Drum"),
    ("Percussive", "Reverse Cymbal"),
    ("Sound Effects", "Guitar Fret Noise"),
    ("Sound Effects", "Breath Noise"),
    ("Sound Effects", "Seashore"),
    ("Sound Effects", "Bird Tweet"),
    ("Sound Effects", "Telephone Ring"),
    ("Sound Effects", "Helicopter"),
    ("Sound Effects", "Applause"),
    ("Sound Effects", "Gunshot")
]